https://app.powerbi.com/view?r=eyJrIjoiMjBiOGJmYzktNGI1NS00NjNiLTkyZTAtNmQ1YmFhNDA5YmZjIiwidCI6ImEzMDYyZjQ0LTllOGEtNDIzOS1hODhjLThjYzMwMzZjZGI0NyIsImMiOjZ9

<iframe width="800" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiMjBiOGJmYzktNGI1NS00NjNiLTkyZTAtNmQ1YmFhNDA5YmZjIiwidCI6ImEzMDYyZjQ0LTllOGEtNDIzOS1hODhjLThjYzMwMzZjZGI0NyIsImMiOjZ9" frameborder="0" allowFullScreen="true"></iframe>

https://www.linkedin.com/pulse/power-bi-coronavirus-report-template-seth-sanusi


https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv


COVID19
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSs7PS8ssyk1NUYrViVZKSU0sySgGM4tSk/PLUotAErEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [StatusData = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"StatusData", type text}}),
    #"Invoked Custom Function" = Table.AddColumn(#"Changed Type", "Sta", each GetStatusData([StatusData])),
    #"Expanded Sta" = Table.ExpandTableColumn(#"Invoked Custom Function", "Sta", {"Province/State", "Country/Region", "Lat", "Long", "Date", "Value"}, {"Province/State", "Country/Region", "Lat", "Long", "Date", "Value"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded Sta",{{"Date", type date}, {"Value", Int64.Type}, {"Long", type number}, {"Lat", type number}, {"Province/State", type text}, {"Country/Region", type text}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([Value] <> null and [Value] <> 0 and [Value] <> ""))
in
    #"Filtered Rows"

GetStatusData
(statusdata as text) =>
let
    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_" & statusdata & "_global.csv"),[Delimiter=",",  Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column54", type text}, {"Column55", type text}, {"Column56", type text}, {"Column57", type text}, {"Column58", type text}, {"Column59", type text}, {"Column60", type text}, {"Column61", type text}, {"Column62", type text}, {"Column63", type text}, {"Column64", type text}, {"Column65", type text}, {"Column66", type text}, {"Column67", type text}, {"Column68", type text}, {"Column69", type text}, {"Column70", type text}, {"Column71", type text}}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Province/State", type text}, {"Country/Region", type text}, {"Lat", type number}, {"Long", type number}, {"1/22/20", Int64.Type}, {"1/23/20", Int64.Type}, {"1/24/20", Int64.Type}, {"1/25/20", Int64.Type}, {"1/26/20", Int64.Type}, {"1/27/20", Int64.Type}, {"1/28/20", Int64.Type}, {"1/29/20", Int64.Type}, {"1/30/20", Int64.Type}, {"1/31/20", Int64.Type}, {"2/1/20", Int64.Type}, {"2/2/20", Int64.Type}, {"2/3/20", Int64.Type}, {"2/4/20", Int64.Type}, {"2/5/20", Int64.Type}, {"2/6/20", Int64.Type}, {"2/7/20", Int64.Type}, {"2/8/20", Int64.Type}, {"2/9/20", Int64.Type}, {"2/10/20", Int64.Type}, {"2/11/20", Int64.Type}, {"2/12/20", Int64.Type}, {"2/13/20", Int64.Type}, {"2/14/20", Int64.Type}, {"2/15/20", Int64.Type}, {"2/16/20", Int64.Type}, {"2/17/20", Int64.Type}, {"2/18/20", Int64.Type}, {"2/19/20", Int64.Type}, {"2/20/20", Int64.Type}, {"2/21/20", Int64.Type}, {"2/22/20", Int64.Type}, {"2/23/20", Int64.Type}, {"2/24/20", Int64.Type}, {"2/25/20", Int64.Type}, {"2/26/20", Int64.Type}, {"2/27/20", Int64.Type}, {"2/28/20", Int64.Type}, {"2/29/20", Int64.Type}, {"3/1/20", Int64.Type}, {"3/2/20", Int64.Type}, {"3/3/20", Int64.Type}, {"3/4/20", Int64.Type}, {"3/5/20", Int64.Type}, {"3/6/20", Int64.Type}, {"3/7/20", Int64.Type}, {"3/8/20", Int64.Type}, {"3/9/20", Int64.Type}, {"3/10/20", Int64.Type}, {"3/11/20", Int64.Type}, {"3/12/20", Int64.Type}, {"3/13/20", Int64.Type}, {"3/14/20", Int64.Type}, {"3/15/20", Int64.Type}, {"3/16/20", Int64.Type}, {"3/17/20", Int64.Type}, {"3/18/20", Int64.Type}, {"3/19/20", Int64.Type}, {"3/20/20", Int64.Type}, {"3/21/20", Int64.Type}, {"3/22/20", Int64.Type}, {"3/23/20", Int64.Type}, {"3/24/20", Int64.Type}, {"3/25/20", Int64.Type}, {"3/26/20", Int64.Type}, {"3/27/20", Int64.Type}, {"3/28/20", Int64.Type}}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Province/State", "Country/Region", "Lat", "Long"}, "Attribute", "Value"),
    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Attribute", "Date"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}})
in
    #"Changed Type2"


Total Conirmd
Total Recovered
Total Deaths
Country News


Country News = "https://www.bing.com/news/search?q=Coronavirus+" & [Country/Region] & " &qft=sortbydate%3d%221%22"

Total Confirmed = CALCULATE(SUM(COVID19[Value])| COVID19[StatusData]="confirmed")
Total Deaths = CALCULATE(SUM(COVID19[Value])| COVID19[StatusData]="deaths")
Total Recovered = CALCULATE(SUM(COVID19[Value])| COVID19[StatusData]="recovered")


Countries Selected = CALCULATE(CONCATENATEX(VALUES(COVID19[Country/Region])|COVID19[Country/Region]|","))


Data: 
John Hopkins University:
https://github.com/CSSEGISandData/COVID-19
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
Terms of Use:
This GitHub repo and its contents herein, including all data, mapping, and analysis, copyright 2020 Johns Hopkins University, all rights reserved, is provided to the public strictly for educational and academic research purposes. The Website relies upon publicly available data from multiple sources, that do not always agree. The Johns Hopkins University hereby disclaims any and all representations and warranties with respect to the Website, including accuracy, fitness for use, and merchantability. Reliance on the Website for medical guidance or use of the Website in commerce is strictly prohibited.

Power BI Ingestion Credit / Acknowledgement / Gratitude to:
Danelly Ramos = AnalyzeWithPower: 
https://www.youtube.com/watch?v=qWHIJikCw-8 

News links Courtesy of Bing.com



LASTDATE(COVID19[Date]))

Current Total = CALCULATE(SUM(COVID19[Value])|LASTDATE(COVID19[Date]))
